# Generated by Django 4.2.10 on 2024-02-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2024-02-20'),
            preserve_default=False,
        ),
    ]
